# Generated by Django 5.0.6 on 2024-06-04 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('PAYTM', 'Paytm'), ('PHONEPE', 'PhonePe')], max_length=30, null=True)),
                ('type', models.CharField(choices=[('CARD', 'card payment'), ('UPI', 'upi'), ('CASH', 'cash'), ('AMAZON_WALLET', 'Amazon wallet')], default='CASH', max_length=20)),
                ('perc_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('perc_cashback', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('CLOTHING', 'clothing'), ('ELECTRONICS', 'electronics'), ('GROCERY', 'Grocery')], max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_id', models.IntegerField()),
                ('description', models.TextField()),
                ('cost', models.IntegerField(max_length=10)),
                ('item_id', models.IntegerField()),
                ('item_photo', models.ImageField(blank=True, default='https://static7.depositphotos.com/1056394/786/v/450/depositphotos_7867981-stock-illustration-vector-cardboard-box.jpg', null=True, upload_to='item_img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_cost', models.IntegerField(max_length=10)),
                ('discounted_cost', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('Bank_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.bank_info')),
                ('items_list', models.ManyToManyField(to='server.items')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg', null=True, upload_to='profile_pics/')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('addr_FullName', models.CharField(blank=True, max_length=30, null=True)),
                ('addr_Phone', models.CharField(blank=True, max_length=10, null=True)),
                ('Flat', models.CharField(blank=True, max_length=100, null=True)),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('amazon_pay_balance', models.IntegerField(default=0, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
