# Generated by Django 5.0.6 on 2024-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='discounted_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='amazon_pay_balance',
            field=models.IntegerField(default=0),
        ),
    ]
