# Generated by Django 5.0.6 on 2024-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_items_cost_alter_orders_discounted_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('GROCERY', 'Grocery')], max_length=25, unique=True),
        ),
    ]
