# Generated by Django 5.0.6 on 2024-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
