# Generated by Django 5.0.6 on 2024-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_items_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items_list',
            new_name='order_items',
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
