# Generated by Django 5.0.6 on 2024-06-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_orders_user_orders_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
