# Generated by Django 5.0.6 on 2024-06-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_delete_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_cost', models.IntegerField(blank=True, default=0)),
                ('discounted_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('savings', models.IntegerField(blank=True, default=0, null=True)),
                ('Bank_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.bank_info')),
                ('order_items', models.ManyToManyField(to='server.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
