# Generated by Django 5.0.6 on 2024-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_info',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('PAYTM', 'Paytm'), ('PHONEPE', 'PhonePe'), ('CASH', 'Cash')], max_length=30, null=True),
        ),
    ]
