# Generated by Django 5.0.6 on 2024-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_set_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_budget',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
