# Generated by Django 5.0.6 on 2024-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_set_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_budget',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
