# Generated by Django 5.0.6 on 2024-06-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_set_budget_electronics_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set_Budget',
        ),
    ]
