# Generated by Django 5.0.6 on 2024-06-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_delete_set_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('clothing_perc', models.IntegerField(default=0)),
                ('electronics_perc', models.IntegerField(default=0)),
                ('grocery_perc', models.IntegerField(default=0)),
                ('clothing_amount', models.IntegerField(default=0)),
                ('electronics_amount', models.IntegerField(default=0)),
                ('grocery_amount', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
