# Generated by Django 5.0.6 on 2024-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_bank_info_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_budget',
            name='above_75',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set_budget',
            name='equal_100',
            field=models.BooleanField(default=False),
        ),
    ]
