# Generated by Django 5.0.6 on 2024-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_set_budget_above_75_set_budget_equal_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='pranavchauhan003@gmail.com', max_length=254),
        ),
    ]
