# Generated by Django 5.0.6 on 2024-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_info',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('KOTAK', 'Kotak Bank'), ('AMEX', 'American Express Bank'), ('PAYTM', 'Paytm'), ('PHONEPE', 'PhonePe UPI'), ('AMAZON_PAY', 'Amazon Pay UPI'), ('CASH', 'Cash'), ('PAYTM_WALLET', 'Paytm Wallet'), ('PHONEPE_WALLET', 'PhonePe Wallet'), ('AMAZON_WALLET', 'Amazon Pay Wallet')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bank_info',
            name='type',
            field=models.CharField(choices=[('CARD', 'card payment'), ('UPI', 'upi'), ('CASH', 'cash'), ('WALLET', 'wallet')], default='CASH', max_length=20),
        ),
    ]
